# Generated by Django 4.2.13 on 2024-06-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoUsers', '0002_alter_customuser_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(blank=True, default='2001-09-11', null=True),
        ),
    ]
