# Generated by Django 4.2.13 on 2024-06-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoUsers', '0003_alter_customuser_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('Student', 'Студент'), ('School', 'Мектеп оқушысы'), ('Teacher', 'Мұғалім'), ('Other', 'Басқа')], default='Student', max_length=10),
        ),
    ]
