# Generated by Django 4.2.13 on 2024-06-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoUsers', '0004_customuser_city_alter_customuser_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subscribe',
            field=models.BooleanField(default=False),
        ),
    ]
