# Generated by Django 4.2.13 on 2024-05-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.TextField(max_length=30)),
                ('lecture_content', models.TextField(max_length=500)),
            ],
        ),
    ]
